In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
sns.set()

import warnings
warnings.filterwarnings('ignore')
import os

In [2]:
crd = pd.read_csv(r"C:\Users\Shivani Dussa\Downloads\creditcard.csv")
crd.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [3]:
crd.shape

(284807, 31)

**RobustScaler:** Unlike the previous scalers, the 
centering and scaling statistics of RobustScaler is based on percentiles and are therefore not influenced by a few number of very large marginal outliers. Consequently, the resulting range of the transformed feature values is larger than for the previous scalers and, more importantly, are approximately similar: for both features most of the transformed values lie in a [-2, 3] range

In [7]:
crd['Amount'].values.shape

(284807,)

In [4]:
from sklearn.preprocessing import RobustScaler
rs = RobustScaler()

#Fit_Transform the scaled_amount and scaled_time columns in the data set and dropping the Original Time and Amount Column from the data set

crd['scaled_amount'] = rs.fit_transform(crd['Amount'].values.reshape(-1,1))
crd['scaled_time'] = rs.fit_transform(crd['Time'].values.reshape(-1,1))
crd.drop(['Time', 'Amount'], axis=1, inplace=True) #Dropping the Original Time and Amount Column from the data set

In [5]:
crd.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Class',
       'scaled_amount', 'scaled_time'],
      dtype='object')

In [6]:
crd = crd[['scaled_amount', 'scaled_time','V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Class']]
crd.head()

,scaled_amount,scaled_time,V1,V2,V3,V4,V5,V6,V7,V8,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Class
0,1.783274,-0.994983,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,...,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,0
1,-0.269825,-0.994983,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,...,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,0
2,4.983721,-0.994972,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,...,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,0
3,1.418291,-0.994972,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,...,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,0
4,0.670579,-0.994960,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,...,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,0

In [7]:
from sklearn.model_selection import train_test_split as tts #Importing the train_test_split from sklearn library
X = np.array(crd.iloc[:, crd.columns != 'Class']) #Predictors 
# x = np.array(df[['scaled_amount', 'scaled_time','V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
#        'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
#        'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28']])
# x = df.drop('Class', axis=1)
y = np.array(crd.iloc[:, crd.columns == 'Class']) #Target Column
X_train, X_test, y_train, y_test = tts(X, y, test_size=0.2, random_state=0) #Splitting the data set into training and testing set

### **Model Boosting**

**Gradient Boosting Classifier**

Parameters

- **n_estimators:** Represents the number of trees in the forest
- **learning_rate:** Shrinks the contribution of each tree by learning_rate.
- **max_features:** Represents the number of features to consider when looking for the best split 
- **max_depth:** Indicates how deep the built tree can be
- **random_state:** Random state ensures that the splits that you generate are reproducible. Used as a seed to the random number generator. This ensures that the random numbers are generated in the same order

In [21]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix, classification_report
#from sklearn.metrics import  accuracy_score, f1_score, precision_score, recall_score, roc_auc_score

gbc = GradientBoostingClassifier(n_estimators=200, learning_rate=0.1, max_features=2, max_depth=2, random_state=0)
gbc.fit(X_train, y_train)

print("Accuracy score (training set): {0:.3f}".format(gbc.score(X_train, y_train)))
print("Accuracy score (testing set): {0:.3f}".format(gbc.score(X_test, y_test)))

pred = gbc.predict(X_test)

print("Confusion Matrix:")
print(confusion_matrix(y_test, pred))

print("Classification Report")
print(classification_report(y_test, pred))

Accuracy score (training set): 0.999
Accuracy score (testing set): 0.999
Confusion Matrix:
[[56835    26]
 [   48    53]]
Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56861
           1       0.67      0.52      0.59       101

    accuracy                           1.00     56962
   macro avg       0.84      0.76      0.79     56962
weighted avg       1.00      1.00      1.00     56962

**Let us try different learning rates to compare the performance of the classifier's performance at different learning rates**

In [33]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import  accuracy_score, f1_score, precision_score, recall_score, roc_auc_score
lr_rate_list = [0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1]

for i in lr_rate_list:
    gbc = GradientBoostingClassifier(n_estimators=20, learning_rate=i, max_features=2, max_depth=2, random_state=0)
    gbc.fit(X_train, y_train)

    print("Learning rate: ", i)
    print("Accuracy score (training set): {0:.3f}".format(gbc.score(X_train, y_train)))
    print("Accuracy score (testing set): {0:.3f}".format(gbc.score(X_test, y_test)))

Learning rate:  0.05
Accuracy score (training set): 0.998
Accuracy score (testing set): 0.999
Learning rate:  0.075
Accuracy score (training set): 0.999
Accuracy score (testing set): 0.999
Learning rate:  0.1
Accuracy score (training set): 0.999
Accuracy score (testing set): 0.999
Learning rate:  0.25
Accuracy score (training set): 0.005
Accuracy score (testing set): 0.006
Learning rate:  0.5
Accuracy score (training set): 0.998
Accuracy score (testing set): 0.998
Learning rate:  0.75
Accuracy score (training set): 0.998
Accuracy score (testing set): 0.998
Learning rate:  1
Accuracy score (training set): 0.998
Accuracy score (testing set): 0.998

**From above, we can see that a learning rate of 0.05 gives us the best performance on the testing set and good performance on the training set**

In [36]:
from sklearn.metrics import classification_report,confusion_matrix
gbc2 = GradientBoostingClassifier(n_estimators = 20,learning_rate = 0.05,max_features = 2,max_depth = 2,random_state = 0)
gbc2.fit(X_train,y_train)
pred1 = gbc2.predict(X_test)

print("classification report:")
print(classification_report(y_test,pred1))

print("confusion matrix:")
print(confusion_matrix(y_test,pred1))

classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56861
           1       0.58      0.66      0.62       101

    accuracy                           1.00     56962
   macro avg       0.79      0.83      0.81     56962
weighted avg       1.00      1.00      1.00     56962

confusion matrix:
[[56812    49]
 [   34    67]]

### observation:
  - **From above, you can see that the Precision and Recall Score is 0.58 and 0.66 respectively. But, we know that the accuracy is close to 99 which can be a misleading factor in this scenario**

## XGBoost
#### Parameters 
- **n_estimators:** Represents the number of trees in the forest
- **learning_rate:** Shrinks the contribution of each tree by learning rate
- **max_depth:** Indicates how deep the built tree can be

In [8]:
import xgboost as xgb

In [9]:
xboost = xgb.XGBClassifier(n_estimators = 1000,learning_rate = 0.01,max_depth = 2)
xboost.fit(X_train,y_train)
pred3 = xboost.predict(X_test)

In [10]:
from sklearn.metrics import classification_report,confusion_matrix

print("classification report:")
print(classification_report(y_test,pred3))

print("confusioin matrix:")
print(confusion_matrix(y_test,pred3))

classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56861
           1       0.92      0.76      0.83       101

    accuracy                           1.00     56962
   macro avg       0.96      0.88      0.92     56962
weighted avg       1.00      1.00      1.00     56962

confusioin matrix:
[[56854     7]
 [   24    77]]

#### **observation:**
    - compraing to all  algorithms xgboost got good values

## Model Intrepetation:Eli5

In [8]:
import eli5 as eli

**show_weights:** Shows the features and their weights

In [26]:
from imblearn.over_sampling import SMOTE
from sklearn import svm

In [11]:
from sklearn.utils import resample
from sklearn.model_selection import train_test_split

In [12]:
from sklearn import svm
from sklearn.metrics import accuracy_score

In [ ]:
eli.show_weights(smote_svm)

### **PyCaret**


Use **PyCaret** to find the best model and perform Automatic Hyperparameter tuning

**PyCaret** is an open source, low-code machine learning library in **Python** that allows you to go from preparing your data to deploying your model within minutes in your choice of notebook environment

[**Click Here!**](https://pycaret.org/) to learn more about **PyCaret**

#### **Tasks to be performed**

- Import PyCaret and load the data set
- Initialize or setup the environment 
- Compare Multiple Models and their Accuracy Metrics
- Create the model
- Tune the model
- Evaluate the model

### *Import PyCaret and load the data set*

In [2]:
import pycaret.classification as pc

In [7]:
%timeit
crd = pd.read_csv(r"C:\Users\Shivani Dussa\Downloads\creditcard.csv")
crd.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,-0.551600,-0.617801,-0.991390,-0.311169,1.468177,-0.470401,0.207971,0.025791,0.403993,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,1.612727,1.065235,0.489095,-0.143772,0.635558,0.463917,-0.114805,-0.183361,-0.145783,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,0.624501,0.066084,0.717293,-0.165946,2.345865,-2.890083,1.109969,-0.121359,-2.261857,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,-0.226487,0.178228,0.507757,-0.287924,-0.631418,-1.059647,-0.684093,1.965775,-1.232622,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,-0.822843,0.538196,1.345852,-1.119670,0.175121,-0.451449,-0.237033,-0.038195,0.803487,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [32]:
crd.shape

(284807, 31)

### *Initialize or setup the environment*

In [5]:
pc.setup(crd,target = 'Class')
%timeit

___
**Observations:**
- The target type (Serial No. 2) is **Binary** because we have two values in **Class** column i.e., **0** and **1**
___

## Compare Multiple Models and their Accuracy Metrics

In [34]:
pc.compare_models()

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
                     oob_score=False, random_state=5659, verbose=0,
                     warm_start=False)

## Create the Model

In [35]:
rf_model = pc.create_model('rf')

## Tune the model

In [ ]:
tuned_rf = pc.tune_model(rf_model)

In [ ]:
print(rf_model)

In [ ]:
print(tuned_rf)

#### see the difference between the orginal model(rf_model) and tune model(tuned_rf)

## Evaluate the Model

In [ ]:
eval_tuned_rf = pc.evaluate_model(tuned_rf)

## **Deploy a web app to predict Fradulent Transactions Using streamlit**

- **Save the next cell as a .py file**
- **Run it in your local system** (streamlit run filename.py)

In [ ]:
import streamlit as st
import pandas as pd
import numpy as np

#Model Building
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

#Data Pre-processing
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import train_test_split

#Model Evaluation
from sklearn.metrics import plot_confusion_matrix, plot_roc_curve, plot_precision_recall_curve
from sklearn.metrics import precision_score, recall_score

def main():
    st.title("Binary Classification Web App")
    st.sidebar.title("Binary Classification Web App")
    st.markdown("Are your transactions fraud or legit?")
    st.sidebar.markdown("Are your transactions fraud or legit?")

    @st.cache(persist=True)
    def load_data():
        df = pd.read_csv("creditcard.csv")

        rs = RobustScaler()
        df['scaled_amount'] = rs.fit_transform(df['Amount'].values.reshape(-1,1))
        df['scaled_time'] = rs.fit_transform(df['Time'].values.reshape(-1,1))
        df.drop(['Time', 'Amount'], axis=1, inplace=True)

        scaled_amount = df['scaled_amount']
        scaled_time = df['scaled_time']
        df.drop(['scaled_amount', 'scaled_time'], axis=1, inplace=True)
        df.insert(0, 'scaled_amount', scaled_amount)
        df.insert(0, 'scaled_time', scaled_time)

        return df
        
    @st.cache(persist=True)
    def split(df):
        from sklearn.model_selection import train_test_split as holdout
        x = np.array(df.iloc[:, df.columns != 'Class'])
        y = np.array(df.iloc[:, df.columns == 'Class'])
        
        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
        return x_train, x_test, y_train, y_test
    
    def plot_metrics(metrics_list):
        if 'Confusion Matrix' in metrics_list:
            st.subheader("Confusion Matrix")
            plot_confusion_matrix(model, x_test, y_test, display_labels=class_names)
            st.pyplot()

        if 'ROC Curve' in metrics_list:
            st.subheader("ROC Curve")
            plot_roc_curve(model, x_test, y_test)
            st.pyplot()
        
        if 'Precision-Recall Curve' in metrics_list:
            st.subheader('Precision-Recall Curve')
            plot_precision_recall_curve(model, x_test, y_test)
            st.pyplot()

    df = load_data()
    class_names = [0, 1]
    
    x_train, x_test, y_train, y_test = split(df)

    st.sidebar.subheader("Choose Classifier")
    classifier = st.sidebar.selectbox("Classifier", ("Support Vector Machine (SVM)", "KNN", "Naive Bayes"))

    if classifier == 'Support Vector Machine (SVM)':
        st.sidebar.subheader("Model Hyperparameters")
        #choose parameters
        C = st.sidebar.number_input("C (Regularization parameter)", 0.01, 10.0, step=0.01, key='C_SVM')
        kernel = st.sidebar.radio("Kernel", ("rbf", "linear"), key='kernel')
        gamma = st.sidebar.radio("Gamma (Kernel Coefficient)", ("scale", "auto"), key='gamma')

        metrics = st.sidebar.multiselect("What metrics to plot?", ('Confusion Matrix', 'ROC Curve', 'Precision-Recall Curve'))
        
        if st.sidebar.button("Classify", key='classify'):
            st.subheader("Support Vector Machine (SVM) Results")
            model = SVC(C=C, kernel=kernel, gamma=gamma)
            model.fit(x_train, y_train)
            accuracy = model.score(x_test, y_test)
            y_pred = model.predict(x_test)
            st.write("Accuracy: ", accuracy.round(2))
            st.write("Precision: ", precision_score(y_test, y_pred, labels=class_names).round(2))
            st.write("Recall: ", recall_score(y_test, y_pred, labels=class_names).round(2))
            plot_metrics(metrics)
    
    if classifier == 'KNN':
        metrics = st.sidebar.multiselect("What metrics to plot?", ('Confusion Matrix', 'ROC Curve', 'Precision-Recall Curve'))

        if st.sidebar.button("Classify", key='classify'):
            st.subheader("KNN Results")
            model = KNeighborsClassifier(n_neighbors=3,metric='euclidean')
            model.fit(x_train, y_train)
            accuracy = model.score(x_test, y_test)
            y_pred = model.predict(x_test)
            st.write("Accuracy: ", accuracy.round(2))
            st.write("Precision: ", precision_score(y_test, y_pred, labels=class_names).round(2))
            st.write("Recall: ", recall_score(y_test, y_pred, labels=class_names).round(2))
            plot_metrics(metrics)
    
    if classifier == 'Naive Bayes':
        metrics = st.sidebar.multiselect("What metrics to plot?", ('Confusion Matrix', 'ROC Curve', 'Precision-Recall Curve'))

        if st.sidebar.button("Classify", key='classify'):
            st.subheader("Naive Bayes Results")
            model = GaussianNB()

            model.fit(x_train, y_train)
            accuracy = model.score(x_test, y_test)
            y_pred = model.predict(x_test)
            st.write("Accuracy: ", accuracy.round(2))
            st.write("Precision: ", precision_score(y_test, y_pred, labels=class_names).round(2))
            st.write("Recall: ", recall_score(y_test, y_pred, labels=class_names).round(2))
            plot_metrics(metrics)

    if st.sidebar.checkbox("Show raw data", False):
        st.subheader("Credit Card Data Set (Classification)")
        st.write(df)
        
if __name__ == '__main__':
    main()